apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ada-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: ada-app.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ada-frontend-service
            port:
              number: 80
